import { Attribute, AttributeType, AttributeInputType } from '../entities/attribute.entity'

export const attributesSeedData: Partial<Attribute>[] = [
  // General Electronics Attributes
  {
    name: 'Brand',
    slug: 'brand',
    description: 'Product manufacturer or brand',
    type: AttributeType.SELECT,
    inputType: AttributeInputType.SELECT,
    options: ['Apple', 'Samsung', 'Xiaomi', 'Huawei', 'LG', 'Sony', 'Dell', 'HP', 'Lenovo', 'Asus', 'Acer', 'MSI'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 1,
    categoryId: null, // Global attribute
  },
  {
    name: 'Color',
    slug: 'color',
    description: 'Product color',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['Black', 'White', 'Silver', 'Gold', 'Blue', 'Red', 'Green', 'Pink', 'Purple', 'Gray'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 2,
    categoryId: null,
  },
  {
    name: 'Warranty Period',
    slug: 'warranty',
    description: 'Warranty period in months',
    type: AttributeType.NUMBER,
    inputType: AttributeInputType.NUMBER,
    options: null,
    unit: 'months',
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 3,
    categoryId: null,
  },
  {
    name: 'Condition',
    slug: 'condition',
    description: 'Product condition',
    type: AttributeType.SELECT,
    inputType: AttributeInputType.RADIO,
    options: ['New', 'Refurbished', 'Used'],
    unit: null,
    isFilterable: true,
    isRequired: true,
    isVisible: true,
    sortOrder: 4,
    categoryId: null,
  },

  // Smartphones & Tablets Attributes
  {
    name: 'Screen Size',
    slug: 'screen-size',
    description: 'Display diagonal size',
    type: AttributeType.RANGE,
    inputType: AttributeInputType.RANGE_SLIDER,
    options: null,
    unit: 'inches',
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 10,
    categoryId: null, // Should be set to smartphones/tablets category
  },
  {
    name: 'RAM',
    slug: 'ram',
    description: 'Random Access Memory',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['2GB', '3GB', '4GB', '6GB', '8GB', '12GB', '16GB', '32GB'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 11,
    categoryId: null,
  },
  {
    name: 'Storage',
    slug: 'storage',
    description: 'Internal storage capacity',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['16GB', '32GB', '64GB', '128GB', '256GB', '512GB', '1TB', '2TB'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 12,
    categoryId: null,
  },
  {
    name: 'Battery Capacity',
    slug: 'battery',
    description: 'Battery capacity',
    type: AttributeType.RANGE,
    inputType: AttributeInputType.RANGE_SLIDER,
    options: null,
    unit: 'mAh',
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 13,
    categoryId: null,
  },
  {
    name: 'Camera Resolution',
    slug: 'camera',
    description: 'Main camera resolution',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['8MP', '12MP', '16MP', '48MP', '64MP', '108MP', '200MP'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 14,
    categoryId: null,
  },
  {
    name: '5G Support',
    slug: '5g-support',
    description: '5G network support',
    type: AttributeType.BOOLEAN,
    inputType: AttributeInputType.CHECKBOX,
    options: null,
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 15,
    categoryId: null,
  },

  // Laptops & Computers Attributes
  {
    name: 'Processor',
    slug: 'processor',
    description: 'CPU model',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['Intel Core i3', 'Intel Core i5', 'Intel Core i7', 'Intel Core i9', 'AMD Ryzen 3', 'AMD Ryzen 5', 'AMD Ryzen 7', 'AMD Ryzen 9', 'Apple M1', 'Apple M2', 'Apple M3'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 20,
    categoryId: null,
  },
  {
    name: 'Graphics Card',
    slug: 'gpu',
    description: 'Graphics processing unit',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['Integrated', 'NVIDIA GTX 1650', 'NVIDIA RTX 3050', 'NVIDIA RTX 3060', 'NVIDIA RTX 4060', 'NVIDIA RTX 4070', 'AMD Radeon RX 6600', 'AMD Radeon RX 7600'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 21,
    categoryId: null,
  },
  {
    name: 'Display Type',
    slug: 'display-type',
    description: 'Screen panel technology',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['IPS', 'OLED', 'AMOLED', 'TN', 'VA', 'Retina'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 22,
    categoryId: null,
  },
  {
    name: 'Operating System',
    slug: 'os',
    description: 'Pre-installed operating system',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['Windows 11', 'Windows 10', 'macOS', 'Linux', 'Chrome OS', 'DOS'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 23,
    categoryId: null,
  },
  {
    name: 'Weight',
    slug: 'weight',
    description: 'Device weight',
    type: AttributeType.RANGE,
    inputType: AttributeInputType.RANGE_SLIDER,
    options: null,
    unit: 'kg',
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 24,
    categoryId: null,
  },

  // Audio/Headphones Attributes
  {
    name: 'Connection Type',
    slug: 'connection',
    description: 'How device connects',
    type: AttributeType.MULTI_SELECT,
    inputType: AttributeInputType.CHECKBOX,
    options: ['Bluetooth', 'Wired', 'USB-C', '3.5mm Jack', 'Wireless 2.4GHz'],
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 30,
    categoryId: null,
  },
  {
    name: 'Noise Cancellation',
    slug: 'noise-cancellation',
    description: 'Active noise cancellation feature',
    type: AttributeType.BOOLEAN,
    inputType: AttributeInputType.CHECKBOX,
    options: null,
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 31,
    categoryId: null,
  },
  {
    name: 'Microphone',
    slug: 'microphone',
    description: 'Built-in microphone',
    type: AttributeType.BOOLEAN,
    inputType: AttributeInputType.CHECKBOX,
    options: null,
    unit: null,
    isFilterable: true,
    isRequired: false,
    isVisible: true,
    sortOrder: 32,
    categoryId: null,
  },

]
